### PR TITLE
Implement issue #40:

### PR DESCRIPTION
**Pull request by echevrier**
- replace safe_indexing() with slice.get
- use slice.get() in safe_indexing_one

### CODE REVIEW

**Comment by clangenb** [comment]
I am fine with keeping `safe_indexing_one` around. But I find it misleading that it returns a `usize`. Furthermore, If we do it like that we can also make it more generic and use it for multiple indexes again.


```
fn safe_indexing<I>(data: &[u8], idx: I)-> Result<u8, &'static str>
where
   I: SliceIndex<u8>
 {
   data.get(idx).ok_or("Index out of bounds")
}

pub fn length_from_raw_data(data: &[u8], offset: &mut usize) -> Result<usize, &'static str> {
    let mut len = safe_indexing(data, *offset)?;
    if len > 0x80 {
        len = (safe_indexing(data, *offset + 1)?) * 0x100
            + (safe_indexing(data, *offset + 2)?);
        *offset += 2;
    }
    Ok(len as usize)
}

**Comment by brenzi** [comment]
why would you want to keep `safe_indexing_one`? Seems odd to me for such a fundamental functionality like indexing

**Comment by clangenb** [comment]
In this case, it makes the handling outside a bit more ergonomic, as we transform the `Option<u8/&[u8]>` into a `Result<u8/&[u8], String>`, which we can `?` in the caller.

**Comment by clangenb** [comment]
> @clangenb : Actually I think it is more readable if we keep the method safe_indexing_one but return a usize and make it private, as it is called only by length_from_raw_data but 3 times.

@echevrier Sorry to be nitpicking again. I must admit, after looking at the result, that I like your suggestion more.

**Comment by brenzi** [comment]
whatever the two of you can agree to shall be fine for me

**Review by clangenb — APPROVED** [review]
Looks good to me! Sorry for my flaky behavior about these details.

**Pull request merged**
