### PR TITLE
assume ra_report is plain mrenclave when compiled with `skip-ias-check` flag

### PR DESCRIPTION
**Pull request by clangenb**
This makes the M8-/M6-integration test pass with `skip-ra` pass.

### CODE REVIEW

**Review by brenzi — CHANGES_REQUESTED** [review]
I don't like the assumption that ra_report is mrenclave. makes the code badly readable. Why not just fill mrenclave with zeroes?

Can you please also add a unit test for the `skip-ias-check` case?

**Comment by clangenb** [comment]
The problem is that our integration tests read the mrenclave from the registry. I wanted to avoid adjusting the test workflows.

**Comment by clangenb** [comment]
I will a unit test.

**Comment by brenzi** [comment]
> 
> 
> The problem is that our integration tests read the mrenclave from the registry. I wanted to avoid adjusting the test workflows.

OK. ifneedbe

**Comment by clangenb** [comment]
Added the unit-tests.

In the future, I'd like this feature flag to be less invasive, but this needs some updates in the worker:
* https://github.com/integritee-network/worker/issues/321

**Pull request merged**
